name: Build and Attest

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: .
